'use client'

import React, { useState } from 'react'
import { BuilderReputation, WalletLog, ProofPacket } from '@/app/lib/types'
import { verifyLogCryptographically } from '@/app/lib/canonicalMessage'

interface ProofPacketModalProps {
  isOpen: boolean
  onClose: () => void
  wallet: string
  reputation: BuilderReputation
  logs: WalletLog[]
}

export default function ProofPacketModal({
  isOpen,
  onClose,
  wallet,
  reputation,
  logs,
}: ProofPacketModalProps) {
  const [copiedLink, setCopiedLink] = useState(false)
  const [copiedMd, setCopiedMd] = useState(false)

  if (!isOpen) return null

  const walletShort = `${wallet.slice(0, 4)}...${wallet.slice(-4)}`
  const verifiedLogs = logs.filter((l) => verifyLogCryptographically(l))
  
  // Sort proofs prioritizing GitHub evidence and recent timestamps
  const topProofs = [...verifiedLogs].sort((a, b) => {
    const aScore = (a.github_url ? 2 : 0) + (a.archival_state === 'archived' ? 2 : 0)
    const bScore = (b.github_url ? 2 : 0) + (b.archival_state === 'archived' ? 2 : 0)
    return bScore - aScore || new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
  }).slice(0, 5)

  const packetUrl = typeof window !== 'undefined' ? `${window.location.origin}/u/${wallet}` : `https://provn-sol.vercel.app/u/${wallet}`

  const generateMarkdownDossier = (): string => {
    let md = `# PROVN Proof Packet — ${walletShort}\n\n`
    md += `**Attested Solana Wallet:** \`${wallet}\`  \n`
    md += `**Verification Protocol:** [PROVN Solana Attestation Layer](${packetUrl})  \n`
    md += `**Verified Proofs:** ${reputation.verifiedProofs} | **Recent (30d):** ${reputation.recentVerifiedProofs} | **Evidence Coverage:** ${reputation.proofsWithGithubEvidence}/${reputation.verifiedProofs}\n\n`
    md += `## Verified Proof-of-Work Records\n\n`

    if (topProofs.length === 0) {
      md += `*No cryptographically verified proofs recorded yet.*\n`
    } else {
      topProofs.forEach((p, idx) => {
        md += `### ${idx + 1}. Proof #${p.id} — ${new Date(p.created_at).toLocaleDateString()}\n`
        md += `- **Claim:** ${p.content}\n`
        md += `- **Cryptographic Verification:** Ed25519 Wallet Signature (Verified ✓)\n`
        if (p.github_url) md += `- **GitHub Evidence:** [${p.github_url}](${p.github_url})\n`
        if (p.evidence_url) md += `- **Evidence Link:** [${p.evidence_url}](${p.evidence_url})\n`
        if (p.irys_tx_id && !p.irys_tx_id.startsWith('powl_')) {
          md += `- **Arweave Provenance:** [gateway.irys.xyz/${p.irys_tx_id}](https://gateway.irys.xyz/${p.irys_tx_id})\n`
        }
        md += `- **Inspect Record:** [provn-sol.vercel.app/proof/${p.id}](https://provn-sol.vercel.app/proof/${p.id})\n\n`
      })
    }

    md += `---\n*Generated by PROVN Protocol — Portable, cryptographically attributable evidence for Solana developers.*`
    return md
  }

  const handleCopyLink = () => {
    navigator.clipboard.writeText(packetUrl)
    setCopiedLink(true)
    setTimeout(() => setCopiedLink(false), 2000)
  }

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownDossier())
    setCopiedMd(true)
    setTimeout(() => setCopiedMd(false), 2000)
  }

  const handleDownloadJson = () => {
    const packet: ProofPacket = {
      protocol: 'PROVN',
      version: '1.0',
      generatedAt: new Date().toISOString(),
      wallet,
      walletShort,
      reputationSummary: {
        verifiedProofs: reputation.verifiedProofs,
        recentVerifiedProofs: reputation.recentVerifiedProofs,
        currentStreak: reputation.currentStreak,
        builderLevel: `Level ${reputation.builderLevel.level} (${reputation.builderLevel.title})`,
        topSkills: reputation.skills.slice(0, 5).map((s) => s.name),
        topProtocols: reputation.protocols.slice(0, 5).map((p) => p.name),
      },
      proofs: topProofs.map((p) => ({
        id: p.id,
        walletAddress: p.wallet_address,
        createdAt: p.created_at,
        content: p.content,
        githubUrl: p.github_url || null,
        evidenceUrl: p.evidence_url || null,
        signature: p.signature,
        nonce: p.nonce,
        domain: p.domain,
        skills: p.skills,
        protocols: p.protocols,
        category: p.category,
        irysTxId: p.irys_tx_id || null,
        archivalState: p.archival_state || 'pending',
        isCryptographicallyVerified: true,
        verificationState: 'VERIFIED',
      })),
      verificationUrl: packetUrl,
      verificationInstructions: 'Verify each proof signature independently using TweetNaCl Ed25519 or via https://provn-sol.vercel.app/proof/<id>.',
    }

    const blob = new Blob([JSON.stringify(packet, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `provn-proof-packet-${walletShort}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  const handleDownloadMarkdown = () => {
    const md = generateMarkdownDossier()
    const blob = new Blob([md], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `provn-proof-packet-${walletShort}.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div
      style={{
        position: 'fixed',
        inset: 0,
        zIndex: 9999,
        background: 'rgba(0,0,0,0.85)',
        backdropFilter: 'blur(8px)',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '16px',
      }}
    >
      <div
        className="terminal-card"
        style={{
          maxWidth: '680px',
          width: '100%',
          maxHeight: '90vh',
          display: 'flex',
          flexDirection: 'column',
          boxShadow: '0 24px 60px rgba(0,0,0,0.9)',
          overflow: 'hidden',
        }}
      >
        {/* Modal Header */}
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '18px 24px', borderBottom: '1px solid var(--border-subtle)' }}>
          <div>
            <div style={{ fontWeight: 800, fontSize: '16px', color: '#ffffff' }}>PROVN Proof Packet</div>
            <div style={{ fontSize: '11px', color: 'var(--text-muted)', marginTop: '2px' }}>
              Portable evidence dossier for grants, DAOs, and bounties
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            style={{ background: 'none', border: 'none', color: 'var(--text-faint)', cursor: 'pointer', fontSize: '18px' }}
          >
            ✕
          </button>
        </div>

        {/* Modal Body */}
        <div style={{ padding: '20px 24px', overflowY: 'auto', flex: 1 }}>
          {/* Summary Strip */}
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))', gap: '8px', marginBottom: '20px' }}>
            <div style={{ background: 'var(--bg-base)', border: '1px solid var(--border-subtle)', padding: '10px 12px', borderRadius: '8px' }}>
              <div style={{ color: 'var(--text-faint)', fontSize: '10px', textTransform: 'uppercase', fontWeight: 600 }}>Builder</div>
              <div style={{ color: '#00ff88', fontWeight: 700, fontSize: '13px', fontFamily: 'var(--font-mono)', marginTop: '2px' }}>{walletShort}</div>
            </div>
            <div style={{ background: 'var(--bg-base)', border: '1px solid var(--border-subtle)', padding: '10px 12px', borderRadius: '8px' }}>
              <div style={{ color: 'var(--text-faint)', fontSize: '10px', textTransform: 'uppercase', fontWeight: 600 }}>Verified Proofs</div>
              <div style={{ color: '#ffffff', fontWeight: 700, fontSize: '13px', fontFamily: 'var(--font-mono)', marginTop: '2px' }}>{reputation.verifiedProofs}</div>
            </div>
            <div style={{ background: 'var(--bg-base)', border: '1px solid var(--border-subtle)', padding: '10px 12px', borderRadius: '8px' }}>
              <div style={{ color: 'var(--text-faint)', fontSize: '10px', textTransform: 'uppercase', fontWeight: 600 }}>Recent (30d)</div>
              <div style={{ color: '#00e5ff', fontWeight: 700, fontSize: '13px', fontFamily: 'var(--font-mono)', marginTop: '2px' }}>{reputation.recentVerifiedProofs}</div>
            </div>
            <div style={{ background: 'var(--bg-base)', border: '1px solid var(--border-subtle)', padding: '10px 12px', borderRadius: '8px' }}>
              <div style={{ color: 'var(--text-faint)', fontSize: '10px', textTransform: 'uppercase', fontWeight: 600 }}>Evidence Coverage</div>
              <div style={{ color: '#ab9ff2', fontWeight: 700, fontSize: '13px', fontFamily: 'var(--font-mono)', marginTop: '2px' }}>{reputation.proofsWithGithubEvidence} / {reputation.verifiedProofs}</div>
            </div>
          </div>

          {/* Curated Proofs Preview */}
          <div style={{ marginBottom: '16px' }}>
            <div style={{ fontSize: '11px', color: 'var(--text-faint)', marginBottom: '10px', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              Curated Evidence Proofs ({topProofs.length}):
            </div>
            <div style={{ display: 'grid', gap: '8px' }}>
              {topProofs.map((p) => (
                <div
                  key={p.id}
                  style={{
                    background: 'var(--bg-base)',
                    border: '1px solid var(--border-subtle)',
                    borderRadius: '8px',
                    padding: '12px 14px',
                  }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '6px' }}>
                    <span style={{ color: '#00ff88', fontWeight: 700, fontSize: '12px', fontFamily: 'var(--font-mono)' }}>Proof #{p.id}</span>
                    <span style={{ color: 'var(--text-faint)', fontSize: '11px', fontFamily: 'var(--font-mono)' }}>{new Date(p.created_at).toLocaleDateString()}</span>
                  </div>
                  <div style={{ color: '#ffffff', marginBottom: '8px', fontSize: '13px', lineHeight: 1.45 }}>{p.content}</div>
                  <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap', fontSize: '11px' }}>
                    <span style={{ color: '#00ff88' }}>✓ Ed25519 Verified</span>
                    {p.github_url && <span style={{ color: '#ab9ff2' }}>🐙 GitHub Attached</span>}
                    {p.irys_tx_id && !p.irys_tx_id.startsWith('powl_') && <span style={{ color: '#00e5ff' }}>📦 Arweave Archived</span>}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Modal Actions */}
        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', justifyContent: 'space-between', padding: '16px 24px', borderTop: '1px solid var(--border-subtle)', background: 'var(--bg-subtle)' }}>
          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              type="button"
              onClick={handleCopyLink}
              className="btn-secondary"
              style={{ fontSize: '11px', padding: '7px 12px' }}
            >
              {copiedLink ? '✓ Copied Link' : '🔗 Copy Link'}
            </button>
            <button
              type="button"
              onClick={handleCopyMarkdown}
              className="btn-secondary"
              style={{ fontSize: '11px', padding: '7px 12px' }}
            >
              {copiedMd ? '✓ Copied Markdown' : '📋 Copy Markdown'}
            </button>
          </div>

          <div style={{ display: 'flex', gap: '8px' }}>
            <button
              type="button"
              onClick={handleDownloadJson}
              className="btn-secondary"
              style={{ fontSize: '11px', padding: '7px 12px', color: '#00e5ff' }}
            >
              ↓ JSON
            </button>
            <button
              type="button"
              onClick={handleDownloadMarkdown}
              className="btn-primary"
              style={{ padding: '7px 14px', fontSize: '11px' }}
            >
              ↓ Markdown Dossier
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
