[package]
name = "provn_anchor"
version = "0.1.0"
description = "PROVN Solana On-Chain Proof Anchor Protocol"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "provn_anchor"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.30.1", features = ["init-if-needed"] }
